### ISSUE TITLE
Problem when register new repository

### ISSUE THREAD

**Issue by nicodeur** [BenRomberg/cordonbleu#2]
Hello,

I have this error  when i add a github repository (cordonbleu.log)

```
 Causing: java.lang.RuntimeException: org.eclipse.jgit.api.errors.TransportException: https://github.com/cerberustesting/cerberus-source.git: cannot open git-upload-pack
! at com.benromberg.cordonbleu.util.ExceptionUtil.convertException(ExceptionUtil.java:11) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at com.benromberg.cordonbleu.service.coderepository.GitRepository.callWithAuthentication(GitRepository.java:87) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at com.benromberg.cordonbleu.service.coderepository.GitRepository.pull(GitRepository.java:94) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at com.benromberg.cordonbleu.service.coderepository.CodeRepositoryService.updateRepository(CodeRepositoryService.java:97) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at com.benromberg.cordonbleu.service.coderepository.CodeRepositoryService.lambda$updateRepositories$0(CodeRepositoryService.java:56) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_121]
! at com.benromberg.cordonbleu.service.coderepository.CodeRepositoryService.updateRepositories(CodeRepositoryService.java:56) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at com.benromberg.cordonbleu.main.task.UpdateCodeRepositoryTask.runTask(UpdateCodeRepositoryTask.java:33) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at com.benromberg.cordonbleu.main.task.AbstractTask.run(AbstractTask.java:33) ~[cordonbleu-main-0.0.1-SNAPSHOT.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
! at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

```

**Comment by BenRomberg** [comment]
@nicodeur hm, it works for me. Googling for "cannot open git-upload-pack" leads to all kinds of suggestions - could be a network issue or something else.

You can also try using SSH by adding the SSH Public Key provided on the "Repositories" page within Cordon Bleu to your GitHub settings and using `git@github.com:cerberustesting/cerberus-source.git` as the "Source URL". Also worked for me.

**Comment by nicodeur** [comment]
@BenRomberg Yes, it must be a proxy problem... I will search and report the solution here

**Comment by BenRomberg** [comment]
Seems to no longer be an issue.
